services:
  server:
    image: shitblog-server
    container_name: server
    # restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - net
    ports:
      - 3000:3000
  db:
    image: postgres:16.2-alpine3.19
    container_name: db
    # restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=blogger
      - POSTGRES_DB=blog
    networks:
      net:
        aliases:
          - db

networks:
  net:
